export const resultaConsulta = [
  {
    uf: "ts",
    npu: "0003489-31.1986.8.07.0013",
    forum: "tes",
    cidade: "tes",
    vara: "tes",
    reu: "tes",
    autor: "tes",
    tipoAcao: "tes",
    valorAcao: "tes",
    dataDistri: "tes",
    advAutor: "tes",
    advRéu: "tes",
  },
  {
    uf: "tes",
    npu: "0003489-31.1986.8.07.0013",
    forum: "asd",
    cidade: "recice",
    vara: "justiã",
    reu: "cristina batista da silva",
    autor: "felipe francisco da silvas",
    tipoAcao: "dkpdpdkpf dopfkfdpksdf sdpofkpsdk",
    valorAcao: "21,00",
    dataDistri: "20/03/1991",
    advAutor: "josevaldo tiarnio da silva",
    advRéu: "josevaldo tiarnio da silva",
  },
  {
    uf: "tes",
    npu: "tes",
    forum: "tes",
    cidade: "tes",
    vara: "tes",
    reu: "tes",
    autor: "tes",
    tipoAcao: "tes",
    valorAcao: "tes",
    dataDistri: "tes",
    advAutor: "tes",
    advRéu: "tes",
  },
  {
    uf: "tes",
    npu: "tes",
    forum: "tes",
    cidade: "tes",
    vara: "tes",
    reu: "tes",
    autor: "tes",
    tipoAcao: "tes",
    valorAcao: "tes",
    dataDistri: "tes",
    advAutor: "tes",
    advRéu: "tes",
  },
  {
    uf: "tes",
    npu: "tes",
    forum: "tes",
    cidade: "tes",
    vara: "tes",
    reu: "tes",
    autor: "tes",
    tipoAcao: "tes",
    valorAcao: "tes",
    dataDistri: "tes",
    advAutor: "tes",
    advRéu: "tes",
  },
];
